// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

import {
  type Client,
  type ClientMeta,
  type Composable,
  formDataBodySerializer,
  type Options as Options2,
  type RequestResult,
  type TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  GetApiAuthByProviderSuccessData,
  GetApiAuthLoginByProviderData,
  GetApiAuthManageInfoData,
  GetApiAuthManageInfoError,
  GetApiAuthManageInfoResponse,
  GetApiHistoryData,
  MapIdentityApiApiAuthConfirmEmailData,
  PostApiAuthForgotPasswordData,
  PostApiAuthForgotPasswordError,
  PostApiAuthLoginData,
  PostApiAuthLoginResponse,
  PostApiAuthManage2FaData,
  PostApiAuthManage2FaError,
  PostApiAuthManage2FaResponse,
  PostApiAuthManageInfoData,
  PostApiAuthManageInfoError,
  PostApiAuthManageInfoResponse,
  PostApiAuthRefreshData,
  PostApiAuthRefreshResponse,
  PostApiAuthRegisterData,
  PostApiAuthRegisterError,
  PostApiAuthResendConfirmationEmailData,
  PostApiAuthResetPasswordData,
  PostApiAuthResetPasswordError,
  PostApiDocumentsConvertData,
} from "./types.gen";
import {
  zGetApiAuthByProviderSuccessPath,
  zGetApiAuthLoginByProviderPath,
  zGetApiAuthManageInfoResponse,
  zMapIdentityApiApiAuthConfirmEmailQuery,
  zPostApiAuthForgotPasswordBody,
  zPostApiAuthLoginBody,
  zPostApiAuthLoginQuery,
  zPostApiAuthLoginResponse,
  zPostApiAuthManage2FaBody,
  zPostApiAuthManage2FaResponse,
  zPostApiAuthManageInfoBody,
  zPostApiAuthManageInfoResponse,
  zPostApiAuthRefreshBody,
  zPostApiAuthRefreshResponse,
  zPostApiAuthRegisterBody,
  zPostApiAuthResendConfirmationEmailBody,
  zPostApiAuthResetPasswordBody,
  zPostApiDocumentsConvertBody,
} from "./zod.gen";

export type Options<
  TComposable extends Composable = "$fetch",
  TData extends TDataShape = TDataShape,
  ResT = unknown,
  DefaultT = undefined,
> = Options2<TComposable, TData, ResT, DefaultT> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const postApiAuthRegister = <
  TComposable extends Composable = "$fetch",
  DefaultT = undefined,
>(
  options: Options<TComposable, PostApiAuthRegisterData, unknown, DefaultT>,
): RequestResult<TComposable, unknown | DefaultT, DefaultT> =>
  (options.client ?? client).post<
    TComposable,
    unknown | DefaultT,
    PostApiAuthRegisterError,
    DefaultT
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zPostApiAuthRegisterBody,
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/auth/register",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const postApiAuthLogin = <
  TComposable extends Composable = "$fetch",
  DefaultT extends PostApiAuthLoginResponse = PostApiAuthLoginResponse,
>(
  options: Options<
    TComposable,
    PostApiAuthLoginData,
    PostApiAuthLoginResponse,
    DefaultT
  >,
): RequestResult<TComposable, PostApiAuthLoginResponse | DefaultT, DefaultT> =>
  (options.client ?? client).post<
    TComposable,
    PostApiAuthLoginResponse | DefaultT,
    unknown,
    DefaultT
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zPostApiAuthLoginBody,
          path: z.never().optional(),
          query: zPostApiAuthLoginQuery.optional(),
        })
        .parseAsync(data),
    responseTransformer: async (data) =>
      await zPostApiAuthLoginResponse.parseAsync(data),
    url: "/api/auth/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const postApiAuthRefresh = <
  TComposable extends Composable = "$fetch",
  DefaultT extends PostApiAuthRefreshResponse = PostApiAuthRefreshResponse,
>(
  options: Options<
    TComposable,
    PostApiAuthRefreshData,
    PostApiAuthRefreshResponse,
    DefaultT
  >,
): RequestResult<
  TComposable,
  PostApiAuthRefreshResponse | DefaultT,
  DefaultT
> =>
  (options.client ?? client).post<
    TComposable,
    PostApiAuthRefreshResponse | DefaultT,
    unknown,
    DefaultT
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zPostApiAuthRefreshBody,
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseTransformer: async (data) =>
      await zPostApiAuthRefreshResponse.parseAsync(data),
    url: "/api/auth/refresh",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const mapIdentityApiApiAuthConfirmEmail = <
  TComposable extends Composable = "$fetch",
  DefaultT = undefined,
>(
  options: Options<
    TComposable,
    MapIdentityApiApiAuthConfirmEmailData,
    unknown,
    DefaultT
  >,
): RequestResult<TComposable, unknown | DefaultT, DefaultT> =>
  (options.client ?? client).get<
    TComposable,
    unknown | DefaultT,
    unknown,
    DefaultT
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: zMapIdentityApiApiAuthConfirmEmailQuery,
        })
        .parseAsync(data),
    url: "/api/auth/confirmEmail",
    ...options,
  });

export const postApiAuthResendConfirmationEmail = <
  TComposable extends Composable = "$fetch",
  DefaultT = undefined,
>(
  options: Options<
    TComposable,
    PostApiAuthResendConfirmationEmailData,
    unknown,
    DefaultT
  >,
): RequestResult<TComposable, unknown | DefaultT, DefaultT> =>
  (options.client ?? client).post<
    TComposable,
    unknown | DefaultT,
    unknown,
    DefaultT
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zPostApiAuthResendConfirmationEmailBody,
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/auth/resendConfirmationEmail",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const postApiAuthForgotPassword = <
  TComposable extends Composable = "$fetch",
  DefaultT = undefined,
>(
  options: Options<
    TComposable,
    PostApiAuthForgotPasswordData,
    unknown,
    DefaultT
  >,
): RequestResult<TComposable, unknown | DefaultT, DefaultT> =>
  (options.client ?? client).post<
    TComposable,
    unknown | DefaultT,
    PostApiAuthForgotPasswordError,
    DefaultT
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zPostApiAuthForgotPasswordBody,
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/auth/forgotPassword",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const postApiAuthResetPassword = <
  TComposable extends Composable = "$fetch",
  DefaultT = undefined,
>(
  options: Options<
    TComposable,
    PostApiAuthResetPasswordData,
    unknown,
    DefaultT
  >,
): RequestResult<TComposable, unknown | DefaultT, DefaultT> =>
  (options.client ?? client).post<
    TComposable,
    unknown | DefaultT,
    PostApiAuthResetPasswordError,
    DefaultT
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zPostApiAuthResetPasswordBody,
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/auth/resetPassword",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const postApiAuthManage2Fa = <
  TComposable extends Composable = "$fetch",
  DefaultT extends PostApiAuthManage2FaResponse = PostApiAuthManage2FaResponse,
>(
  options: Options<
    TComposable,
    PostApiAuthManage2FaData,
    PostApiAuthManage2FaResponse,
    DefaultT
  >,
): RequestResult<
  TComposable,
  PostApiAuthManage2FaResponse | DefaultT,
  DefaultT
> =>
  (options.client ?? client).post<
    TComposable,
    PostApiAuthManage2FaResponse | DefaultT,
    PostApiAuthManage2FaError,
    DefaultT
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zPostApiAuthManage2FaBody,
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseTransformer: async (data) =>
      await zPostApiAuthManage2FaResponse.parseAsync(data),
    url: "/api/auth/manage/2fa",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const getApiAuthManageInfo = <
  TComposable extends Composable = "$fetch",
  DefaultT extends GetApiAuthManageInfoResponse = GetApiAuthManageInfoResponse,
>(
  options: Options<
    TComposable,
    GetApiAuthManageInfoData,
    GetApiAuthManageInfoResponse,
    DefaultT
  >,
): RequestResult<
  TComposable,
  GetApiAuthManageInfoResponse | DefaultT,
  DefaultT
> =>
  (options.client ?? client).get<
    TComposable,
    GetApiAuthManageInfoResponse | DefaultT,
    GetApiAuthManageInfoError,
    DefaultT
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseTransformer: async (data) =>
      await zGetApiAuthManageInfoResponse.parseAsync(data),
    url: "/api/auth/manage/info",
    ...options,
  });

export const postApiAuthManageInfo = <
  TComposable extends Composable = "$fetch",
  DefaultT extends PostApiAuthManageInfoResponse =
    PostApiAuthManageInfoResponse,
>(
  options: Options<
    TComposable,
    PostApiAuthManageInfoData,
    PostApiAuthManageInfoResponse,
    DefaultT
  >,
): RequestResult<
  TComposable,
  PostApiAuthManageInfoResponse | DefaultT,
  DefaultT
> =>
  (options.client ?? client).post<
    TComposable,
    PostApiAuthManageInfoResponse | DefaultT,
    PostApiAuthManageInfoError,
    DefaultT
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zPostApiAuthManageInfoBody,
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseTransformer: async (data) =>
      await zPostApiAuthManageInfoResponse.parseAsync(data),
    url: "/api/auth/manage/info",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const postApiDocumentsConvert = <
  TComposable extends Composable = "$fetch",
  DefaultT = undefined,
>(
  options: Options<TComposable, PostApiDocumentsConvertData, unknown, DefaultT>,
): RequestResult<TComposable, unknown | DefaultT, DefaultT> =>
  (options.client ?? client).post<
    TComposable,
    unknown | DefaultT,
    unknown,
    DefaultT
  >({
    ...formDataBodySerializer,
    requestValidator: async (data) =>
      await z
        .object({
          body: zPostApiDocumentsConvertBody,
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/documents/convert",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  });

export const getApiAuthLoginByProvider = <
  TComposable extends Composable = "$fetch",
  DefaultT = undefined,
>(
  options: Options<
    TComposable,
    GetApiAuthLoginByProviderData,
    unknown,
    DefaultT
  >,
): RequestResult<TComposable, unknown | DefaultT, DefaultT> =>
  (options.client ?? client).get<
    TComposable,
    unknown | DefaultT,
    unknown,
    DefaultT
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zGetApiAuthLoginByProviderPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/auth/login/{provider}",
    ...options,
  });

export const getApiAuthByProviderSuccess = <
  TComposable extends Composable = "$fetch",
  DefaultT = undefined,
>(
  options: Options<
    TComposable,
    GetApiAuthByProviderSuccessData,
    unknown,
    DefaultT
  >,
): RequestResult<TComposable, unknown | DefaultT, DefaultT> =>
  (options.client ?? client).get<
    TComposable,
    unknown | DefaultT,
    unknown,
    DefaultT
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zGetApiAuthByProviderSuccessPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/auth/{provider}-success",
    ...options,
  });

export const getApiHistory = <
  TComposable extends Composable = "$fetch",
  DefaultT = undefined,
>(
  options: Options<TComposable, GetApiHistoryData, unknown, DefaultT>,
): RequestResult<TComposable, unknown | DefaultT, DefaultT> =>
  (options.client ?? client).get<
    TComposable,
    unknown | DefaultT,
    unknown,
    DefaultT
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/history",
    ...options,
  });
