// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

export const zAccessTokenResponse = z.object({
  tokenType: z.string().nullish(),
  accessToken: z.string(),
  expiresIn: z.union([
    z.coerce
      .bigint()
      .min(BigInt("-9223372036854775808"), {
        error: "Invalid value: Expected int64 to be >= -9223372036854775808",
      })
      .max(BigInt("9223372036854775807"), {
        error: "Invalid value: Expected int64 to be <= 9223372036854775807",
      }),
    z.coerce
      .bigint()
      .min(BigInt("-9223372036854775808"), {
        error: "Invalid value: Expected int64 to be >= -9223372036854775808",
      })
      .max(BigInt("9223372036854775807"), {
        error: "Invalid value: Expected int64 to be <= 9223372036854775807",
      }),
  ]),
  refreshToken: z.string(),
});

export type AccessTokenResponseZodType = z.infer<typeof zAccessTokenResponse>;

export const zForgotPasswordRequest = z.object({
  email: z.string(),
});

export type ForgotPasswordRequestZodType = z.infer<
  typeof zForgotPasswordRequest
>;

export const zHttpValidationProblemDetails = z.object({
  type: z.string().nullish(),
  title: z.string().nullish(),
  status: z
    .union([
      z
        .int()
        .min(-2147483648, {
          error: "Invalid value: Expected int32 to be >= -2147483648",
        })
        .max(2147483647, {
          error: "Invalid value: Expected int32 to be <= 2147483647",
        }),
      z.string().regex(/^-?(?:0|[1-9]\d*)$/),
    ])
    .nullish(),
  detail: z.string().nullish(),
  instance: z.string().nullish(),
  errors: z.record(z.string(), z.array(z.string())).optional(),
});

export type HttpValidationProblemDetailsZodType = z.infer<
  typeof zHttpValidationProblemDetails
>;

export const zIFormFile = z.string();

export type IFormFileZodType = z.infer<typeof zIFormFile>;

export const zInfoRequest = z.object({
  newEmail: z.string().nullish(),
  newPassword: z.string().nullish(),
  oldPassword: z.string().nullish(),
});

export type InfoRequestZodType = z.infer<typeof zInfoRequest>;

export const zInfoResponse = z.object({
  email: z.string(),
  isEmailConfirmed: z.boolean(),
});

export type InfoResponseZodType = z.infer<typeof zInfoResponse>;

export const zLoginRequest = z.object({
  email: z.string(),
  password: z.string(),
  twoFactorCode: z.string().nullish(),
  twoFactorRecoveryCode: z.string().nullish(),
});

export type LoginRequestZodType = z.infer<typeof zLoginRequest>;

export const zRefreshRequest = z.object({
  refreshToken: z.string(),
});

export type RefreshRequestZodType = z.infer<typeof zRefreshRequest>;

export const zRegisterRequest = z.object({
  email: z.string(),
  password: z.string(),
});

export type RegisterRequestZodType = z.infer<typeof zRegisterRequest>;

export const zResendConfirmationEmailRequest = z.object({
  email: z.string(),
});

export type ResendConfirmationEmailRequestZodType = z.infer<
  typeof zResendConfirmationEmailRequest
>;

export const zResetPasswordRequest = z.object({
  email: z.string(),
  resetCode: z.string(),
  newPassword: z.string(),
});

export type ResetPasswordRequestZodType = z.infer<typeof zResetPasswordRequest>;

export const zTwoFactorRequest = z.object({
  enable: z.boolean().nullish(),
  twoFactorCode: z.string().nullish(),
  resetSharedKey: z.boolean().optional(),
  resetRecoveryCodes: z.boolean().optional(),
  forgetMachine: z.boolean().optional(),
});

export type TwoFactorRequestZodType = z.infer<typeof zTwoFactorRequest>;

export const zTwoFactorResponse = z.object({
  sharedKey: z.string(),
  recoveryCodesLeft: z.union([
    z
      .int()
      .min(-2147483648, {
        error: "Invalid value: Expected int32 to be >= -2147483648",
      })
      .max(2147483647, {
        error: "Invalid value: Expected int32 to be <= 2147483647",
      }),
    z.string().regex(/^-?(?:0|[1-9]\d*)$/),
  ]),
  recoveryCodes: z.array(z.string()).nullish(),
  isTwoFactorEnabled: z.boolean(),
  isMachineRemembered: z.boolean(),
});

export type TwoFactorResponseZodType = z.infer<typeof zTwoFactorResponse>;

export const zPostApiAuthRegisterBody = zRegisterRequest;

export type PostApiAuthRegisterBodyZodType = z.infer<
  typeof zPostApiAuthRegisterBody
>;

export const zPostApiAuthLoginBody = zLoginRequest;

export type PostApiAuthLoginBodyZodType = z.infer<typeof zPostApiAuthLoginBody>;

export const zPostApiAuthLoginQuery = z.object({
  useCookies: z.boolean().optional(),
  useSessionCookies: z.boolean().optional(),
});

export type PostApiAuthLoginQueryZodType = z.infer<
  typeof zPostApiAuthLoginQuery
>;

/**
 * OK
 */
export const zPostApiAuthLoginResponse = zAccessTokenResponse;

export type PostApiAuthLoginResponseZodType = z.infer<
  typeof zPostApiAuthLoginResponse
>;

export const zPostApiAuthRefreshBody = zRefreshRequest;

export type PostApiAuthRefreshBodyZodType = z.infer<
  typeof zPostApiAuthRefreshBody
>;

/**
 * OK
 */
export const zPostApiAuthRefreshResponse = zAccessTokenResponse;

export type PostApiAuthRefreshResponseZodType = z.infer<
  typeof zPostApiAuthRefreshResponse
>;

export const zMapIdentityApiApiAuthConfirmEmailQuery = z.object({
  userId: z.string(),
  code: z.string(),
  changedEmail: z.string().optional(),
});

export type MapIdentityApiApiAuthConfirmEmailQueryZodType = z.infer<
  typeof zMapIdentityApiApiAuthConfirmEmailQuery
>;

export const zPostApiAuthResendConfirmationEmailBody =
  zResendConfirmationEmailRequest;

export type PostApiAuthResendConfirmationEmailBodyZodType = z.infer<
  typeof zPostApiAuthResendConfirmationEmailBody
>;

export const zPostApiAuthForgotPasswordBody = zForgotPasswordRequest;

export type PostApiAuthForgotPasswordBodyZodType = z.infer<
  typeof zPostApiAuthForgotPasswordBody
>;

export const zPostApiAuthResetPasswordBody = zResetPasswordRequest;

export type PostApiAuthResetPasswordBodyZodType = z.infer<
  typeof zPostApiAuthResetPasswordBody
>;

export const zPostApiAuthManage2FaBody = zTwoFactorRequest;

export type PostApiAuthManage2FaBodyZodType = z.infer<
  typeof zPostApiAuthManage2FaBody
>;

/**
 * OK
 */
export const zPostApiAuthManage2FaResponse = zTwoFactorResponse;

export type PostApiAuthManage2FaResponseZodType = z.infer<
  typeof zPostApiAuthManage2FaResponse
>;

/**
 * OK
 */
export const zGetApiAuthManageInfoResponse = zInfoResponse;

export type GetApiAuthManageInfoResponseZodType = z.infer<
  typeof zGetApiAuthManageInfoResponse
>;

export const zPostApiAuthManageInfoBody = zInfoRequest;

export type PostApiAuthManageInfoBodyZodType = z.infer<
  typeof zPostApiAuthManageInfoBody
>;

/**
 * OK
 */
export const zPostApiAuthManageInfoResponse = zInfoResponse;

export type PostApiAuthManageInfoResponseZodType = z.infer<
  typeof zPostApiAuthManageInfoResponse
>;

export const zPostApiDocumentsConvertBody = z.object({
  File: zIFormFile.optional(),
  TargetFormat: z.string().min(0).max(30).optional(),
});

export type PostApiDocumentsConvertBodyZodType = z.infer<
  typeof zPostApiDocumentsConvertBody
>;

export const zGetApiAuthLoginByProviderPath = z.object({
  provider: z.string(),
});

export type GetApiAuthLoginByProviderPathZodType = z.infer<
  typeof zGetApiAuthLoginByProviderPath
>;

export const zGetApiAuthByProviderSuccessPath = z.object({
  provider: z.string(),
});

export type GetApiAuthByProviderSuccessPathZodType = z.infer<
  typeof zGetApiAuthByProviderSuccessPath
>;
